version: "3.6"
services:
  # mongodb:
  #   image: mongo
  #   ports:
  #     - 27013:27017

  server:
    image: alexburlacu/rtp-server:faf18x
    ports:
      - 4000:4000

  broker:
    build:
      context: broker
    ports:
      - 6666:6666

  analyzer:
    build:
      context: analyzer

    depends_on:
      - server
      - broker
